### ISSUE TITLE
Error when building : Invalid value used as weak map key

### ISSUE THREAD

**Issue by robthepaper** [ctwhome/top-nuxt3#16]
Hi, has anyone encounter this error?
used `pnpm install`
then `pnpm build`
and `pnpm start`

`Listening on http://localhost:3000/
Invalid value used as weak map key
  at WeakMap.set (<anonymous>)
  at normalizePropsOptions (file:///D:/NUXT3/top-nuxt3/.output/server/chunks/index.mjs:4583:11)
  at createComponentInstance (file:///D:/NUXT3/top-nuxt3/.output/server/chunks/index.mjs:7411:23)
  at renderComponentVNode (file:///D:/NUXT3/top-nuxt3/.output/server/chunks/index.mjs:9840:22)
  at Object.ssrRenderComponent (file:///D:/NUXT3/top-nuxt3/.output/server/chunks/index.mjs:10272:12)
  at file:///D:/NUXT3/top-nuxt3/.output/server/chunks/server2.mjs:6552:36
  at renderComponentSubTree (file:///D:/NUXT3/top-nuxt3/.output/server/chunks/index.mjs:9912:13)
  at renderComponentVNode (file:///D:/NUXT3/top-nuxt3/.output/server/chunks/index.mjs:9857:16)
  at Object.ssrRenderComponent (file:///D:/NUXT3/top-nuxt3/.output/server/chunks/index.mjs:10272:12)
  at file:///D:/NUXT3/top-nuxt3/.output/server/chunks/server2.mjs:6687:38`

**Comment by robthepaper** [comment]
ok, so I went in dev mode

then found what breaks it : 
`[Vue warn]: Failed to resolve component: icon
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Invalid value used as weak map key`

if I removed in index.vue 
`<Icon icon="mdi-light:home" width="48"/>
            <Icon icon="ion:ios-cart" width="48"/>
            <Icon icon="noto:anchor" width="48"/>
            <Icon icon="fxemoji:alien" width="48"/>`

as well as all icon components in UserLoginForm.vue

the error is gone.

Can someone help me solve this issue ?
