### ISSUE TITLE
I get this error. 

### ISSUE THREAD

**Issue by Dinibewerbig** [ctwhome/top-nuxt3#7]
ENOENT: no such file or directory, stat '/Volumes/Old OS/marti/Downloads/top-nuxt3-main 2/.output/public/_nuxt/manifest.webmanifest'

**Comment by ctwhome** [comment]
thanks for the issue, I can't seem to find the error myself @userquin could you give a hand on this? thank you very much!

**Comment by userquin** [comment]
@Dinibewerbig 

The error is on build or when serving the app once built (it seems it is on serve if the error comes from stat)?
Can you confirm if the directory is there when you run build command? If so, you need to review `build-pwa.ts` module, it has been removed (the content), just enable it again.

**Comment by GithubMitch** [comment]
Nuxt CLI v3.0.0-27409835.c53c736                                                   17:46:43
                                                                                   17:46:43
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.59.3:3000/
  > Network:  http://192.168.59.12:3000/

                                                                                   17:46:46
🌼 daisyUI components 1.25.4  https://github.com/saadeghi/daisyui                  17:46:46
✔︎ Including:  base, components, themes[22], utilities                             17:46:46
                                                                                   17:46:46
ℹ Vite warmed up in 1125ms                                                         17:46:47
ℹ Vite warmed up in 240ms                                                          17:46:47
                                                                                   17:46:48
🌼 daisyUI components 1.25.4  https://github.com/saadeghi/daisyui                  17:46:48
✔︎ Including:  base, components, themes[22], utilities                             17:46:48
                                                                                   17:46:48

 WARN  [SSR] Error transforming /Users/mseedorf/Projects/top-nuxt3/components/MemoryUsageDemo.vue: Failed to resolve import "@vueuse/core" from "components/MemoryUsageDemo.vue". Does the file exist?

  at formatError (node_modules/vite/dist/node/chunks/dep-971d9e33.js:38082:46)
  at TransformContext.error (node_modules/vite/dist/node/chunks/dep-971d9e33.js:38078:19)
  at normalizeUrl (node_modules/vite/dist/node/chunks/dep-971d9e33.js:69803:26)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async TransformContext.transform (node_modules/vite/dist/node/chunks/dep-971d9e33.js:69943:57)
  at async Object.transform (node_modules/vite/dist/node/chunks/dep-971d9e33.js:38318:30)
  at async doTransform (node_modules/vite/dist/node/chunks/dep-971d9e33.js:53014:29)

✔ Vite server built in 1805ms                                                      17:46:49
✔ Nitro built in 144 ms                                                            17:46:49
You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.
[Vue Router warn]: No match found for location with path "/api"
[Vue warn]: Failed to resolve component: icon
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: icon
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Invalid value used as weak map key
  at WeakMap.set (<anonymous>)  
  at normalizePropsOptions (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3384:11)  
  at createComponentInstance (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6839:23)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)  
  at _sfc_ssrRender (file://./.nuxt/dist/server/server.mjs:7751:31)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)  
  at _sfc_ssrRender (file://./.nuxt/dist/server/server.mjs:2566:33)
Invalid value used as weak map key
  at WeakMap.set (<anonymous>)  
  at normalizePropsOptions (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3384:11)  
  at createComponentInstance (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6839:23)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)  
  at _sfc_ssrRender (file://./.nuxt/dist/server/server.mjs:7751:31)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)  
  at _sfc_ssrRender (file://./.nuxt/dist/server/server.mjs:2566:33)
[Vue Router warn]: No match found for location with path "/api"

 ERROR  [worker] Invalid value used as weak map key                                17:46:50

  at WeakMap.set (<anonymous>)
  at normalizePropsOptions (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3384:11)
  at createComponentInstance (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6839:23)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
  at Module.ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)
  at _sfc_ssrRender (.nuxt/dist/server/server.mjs:7751:31)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
  at Module.ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)
  at _sfc_ssrRender (.nuxt/dist/server/server.mjs:2566:33)


 ERROR  [proxy] socket hang up                                                     17:46:50

  at connResetException (node:internal/errors:691:14)
  at Socket.socketOnEnd (node:_http_client:471:23)
  at Socket.emit (node:events:402:35)
  at Socket.emit (node:domain:475:12)
  at endReadableNT (node:internal/streams/readable:1343:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)


Straight up cloned > npm install > npm run dev > Error !
